In [1]:
import numpy as np

In [2]:
np.array(range(4))

array([0, 1, 2, 3])

In [3]:
np.arange(4)

array([0, 1, 2, 3])

In [4]:
x = np.arange(0.5, 4, 1)
x

array([0.5, 1.5, 2.5, 3.5])

In [5]:
x[1] = 2
x

array([0.5, 2. , 2.5, 3.5])

In [6]:
x.shape

(4,)

In [7]:
x.T.shape

(4,)

In [8]:
X = np.array([range(4), range(4)])
X

array([[0, 1, 2, 3],
       [0, 1, 2, 3]])

In [9]:
X.shape

(2, 4)

In [10]:
X.T.shape

(4, 2)

In [11]:
A = np.array([[1, 2, 3], [4, 5, 6]])
A

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
A.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
np.diff(A, axis=0)

array([[3, 3, 3]])

In [15]:
A[1] - A[0]

array([3, 3, 3])

In [36]:
vector1 = []
for i in range(10):
    vector1.append(np.random.random())
vector1

[0.6411233438671461,
 0.4765861088991228,
 0.9250502393154966,
 0.8881366136388935,
 0.9032236958205122,
 0.4378650385543653,
 0.5517668160965681,
 0.23068364779665884,
 0.6442421347051602,
 0.293212665845223]

In [37]:
vector2 = []
for i in range(10):
    vector2.append(np.random.random())
vector2

[0.9945083128710948,
 0.6231130417777987,
 0.5909485491642359,
 0.9342057307644144,
 0.1977038450961468,
 0.8972303103673154,
 0.6917794002086743,
 0.08451717732210129,
 0.7841160788281357,
 0.44556758031069965]

In [40]:
euclidean_distance = np.sqrt(((np.array(vector1) - np.array(vector2)) ** 2).sum())
euclidean_distance

1.0259712447297749

In [46]:
import numpy as np
vector_query = np.array([1, 1])
vector_towndandcountry = np.array([1, 0])
vector_wired = np.array([5, 6])
normalized_query = vector_query / np.linalg.norm(vector_query)
normalized_towndandcountry = vector_tc / np.linalg.norm(vector_towndandcountry)
normalized_wired = vector_wired / np.linalg.norm(vector_wired)

In [67]:
euclidean_distance_tc_wired = np.sqrt(((normalized_towndandcountry - normalized_wired) ** 2).sum())
euclidean_distance_tc_wired

0.8483107924994472

In [65]:
euclidean_distance_tc = np.sqrt(((normalized_query - normalized_towndandcountry) ** 2).sum())
euclidean_distance_tc

0.7653668647301795

In [66]:
euclidean_distance_wired = np.sqrt(((normalized_query - normalized_wired) ** 2).sum())
euclidean_distance_wired

0.0906288423438825

In [42]:
normalized_query

array([0.70710678, 0.70710678])

In [47]:
normalized_towndandcountry

array([1., 0.])

In [48]:
normalized_wired

array([0.6401844 , 0.76822128])

In [52]:
cos_sim_townandcountry = np.dot(normalized_query, normalized_towndandcountry)
cos_sim_townandcountry

0.7071067811865475

In [53]:
cos_sim_wired = np.dot(normalized_query, normalized_wired)
cos_sim_wired

0.9958932064677037

In [55]:
cos_distance_townandcountry = 1 - cos_sim_townandcountry
cos_distance_townandcountry

0.29289321881345254

In [56]:
cos_distance_wired =  1 - cos_sim_wired
cos_distance_wired

0.00410679353229626

### Manhattan Distance

In [60]:
vector_tc = np.array([1, 0])
vector_wired = np.array([5, 6])
np.abs(vector_tc - vector_wired).sum()

10

In [61]:
normalized_tc = vector_tc / np.linalg.norm(vector_tc)
normalized_wired = vector_wired / np.linalg.norm(vector_wired)
np.abs(normalized_tc - normalized_wired).sum()

1.128036879932896